name: rust-crossbuild

on:
    push:
      branches: [ latest ]
      paths:
        - 'Dockerfile.rust-crossbuild'
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}/rust-crossbuild
    BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login into registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Prepare Docker buildx container
              run: docker buildx create --name driver --driver docker-container --use

            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
            - name: Build and publish
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile.rust-crossbuild
                  push: True
                  tags: ${{ steps.meta.outputs.tags }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
